# Generated by Django 3.2.11 on 2022-05-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220513_2349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='titles',
            table='titles',
        ),
        migrations.DeleteModel(
            name='EmployyesDatabase',
        ),
    ]
