# Generated by Django 3.0.5 on 2022-05-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220525_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlesName',
            fields=[
                ('title_no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'titles_name',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='titles',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Employees'),
        ),
    ]
