# Generated by Django 3.0.5 on 2022-05-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20220529_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Employees'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='title',
            field=models.ForeignKey(db_column='title_no', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TitlesName'),
        ),
        migrations.AlterField(
            model_name='titlesname',
            name='title_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
