# Generated by Django 3.0.5 on 2022-06-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20220531_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefunctions',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Employees'),
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Employees'),
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='to_date',
            field=models.DateField(default='9999-01-01'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Employees'),
        ),
        migrations.AlterUniqueTogether(
            name='presencelog',
            unique_together={('emp_no', 'from_date')},
        ),
        migrations.RemoveField(
            model_name='presencelog',
            name='func_assessment',
        ),
        migrations.RemoveField(
            model_name='presencelog',
            name='func_no',
        ),
        migrations.CreateModel(
            name='EmpTaskList',
            fields=[
                ('emp_no', models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Employees')),
                ('new_func_assessment', models.FloatField()),
                ('date', models.DateField()),
                ('to_date', models.DateField()),
                ('func_no', models.ForeignKey(db_column='func_no', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Functions')),
            ],
            options={
                'db_table': 'emp_task_list',
                'managed': True,
                'unique_together': {('emp_no', 'func_no', 'new_func_assessment', 'date', 'to_date')},
            },
        ),
    ]
